# Generated by Django 5.1.4 on 2024-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_at', models.DateTimeField(null=True)),
                ('reserved_by', models.CharField(max_length=7, null=True)),
            ],
        ),
    ]
