global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prober'
    static_configs:
      - targets: ['prober:8080']  # Use the service name instead of localhost
    metrics_path: '/metrics'
    scrape_interval: 5s  # More frequent scraping for the prober

  # Keep Prometheus's own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']