groups:
  - name: prober_alerts
    rules:
      - alert: ReadProbeFailureRate
        expr: |
          (
            rate(probe_sent_total[5m]) 
            - 
            rate(probe_success_total[5m])
          ) 
          / 
          rate(probe_sent_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: warning
          probe_type: read
        annotations:
          summary: "High read probe failure rate"
          description: "Read probe failure rate is above 10% for the last 5 minutes"

      - alert: WriteProbeFailureRate
        expr: |
          (
            rate(probe_sent_total[5m]) 
            - 
            rate(probe_success_total[5m])
          ) 
          / 
          rate(probe_sent_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: warning
          probe_type: write
        annotations:
          summary: "High write probe failure rate"
          description: "Write probe failure rate is above 10% for the last 5 minutes"

      - alert: HighProbeLatency
        expr: histogram_quantile(0.95, rate(probe_latency_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High probe latency"
          description: "95th percentile latency is above 1 second for the last 5 minutes"

      - alert: ProberDown
        expr: up{job="prober"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Prober is down"
          description: "Prober service is not responding"
