# version: "3.9" || Obsolete
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django-backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./ActiveMETU-Django:/django
    depends_on:
      - postgres

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.expo
  #   container_name: expo-frontend
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_PORT=19002
  #   volumes:
  #     - ./ActiveMETU-Expo:/app
  #     - /app/node_modules
  #   stdin_open: true
  #   tty: true

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
volumes:
  postgres_data:
