FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential gcc \
    libpq-dev \
    libexpat1-dev \
    apache2-dev 

# Set working directory
WORKDIR /django

COPY ActiveMETU-Django /django/

RUN pip install -r requirements.txt

# Run the Django development server
CMD ["sh", "-c", "python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8080"]
