# Generated by Django 5.1.4 on 2024-12-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('registration_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
